version: "3"
services:          
    mysql_gtfsloader:
        image: mysql:5.5.59
        container_name: mysql_GTFSLoader
        environment:
            MYSQL_ROOT_PASSWORD: confluent
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            MYSQL_DATABASE: connect_test
            #        depends_on:
            #- kafka-connect
            #        volumes:
            # - mysql_gtfsloader:/var/lib/mysql
            #ports:
            #- 3308:3306
    gtfsloader:
        image: sparsitytechnologies/gtfsloader:latest
        container_name: gtfsloader
        depends_on:
            - mysql_gtfsloader
        ports:
            - "4567:4567"
        environment:
            KAFKA_CONNECT_HOST: kafka-connect
            MYSQL_HOST: mysql_GTFSLoader
            MYSQL_PASSWORD: confluent
            ELASTIC_TOPICS: "cigo-jdbc-trips, cigo-jdbc-stops,cigo-jdbc-routes,cigo-jdbc-stop_times,cigo-jdbc-calendar_dates,cigo-jdbc-calendar,cigo-jdbc-frequencies,cigo-jdbc-transfers,cigo-jdbc-agency,cigo-jdbc-cigo-jdbc-feed_info,cigo-jdbc-shapes"
networks:
    default:
        external:
            name: cigo-compose_default
            #volumes:
            #    mysql_gtfsloader:
